
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ruşan Oğuz
 */
public class RezPage extends javax.swing.JFrame {
    HotelOperations ops =new HotelOperations();
    /**
     * Creates new form RezPage
     */
    public RezPage() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        EkoRadio = new javax.swing.JRadioButton();
        StanRadio = new javax.swing.JRadioButton();
        BSRadio = new javax.swing.JRadioButton();
        KralRadio = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        RezName = new javax.swing.JTextField();
        RezSurname = new javax.swing.JTextField();
        RezAge = new javax.swing.JTextField();
        RezId = new javax.swing.JTextField();
        RezPhone = new javax.swing.JTextField();
        RezMemnumber = new javax.swing.JTextField();
        RezEnDay = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        RezEnMonth = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        RezExDay = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        RezExMonth = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        RezExYear = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        RezDoneButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setText("Rezervasyon Sayfası");

        jLabel2.setText("İsim:");

        jLabel3.setText("Soyisim:");

        jLabel4.setText("Yaş:");

        jLabel5.setText("TC:");

        jLabel6.setText("Telefon:");

        jLabel7.setText("Kişi Sayısı:");

        buttonGroup1.add(EkoRadio);
        EkoRadio.setSelected(true);
        EkoRadio.setText("Ekonomik Oda");

        buttonGroup1.add(StanRadio);
        StanRadio.setText("Standart Oda");

        buttonGroup1.add(BSRadio);
        BSRadio.setText("Balayı Suiti");

        buttonGroup1.add(KralRadio);
        KralRadio.setText("Kral Dairesi");

        jLabel8.setText("Giriş Tarihi:");

        jLabel9.setText("Çıkış Tarihi:");

        jLabel10.setText("-");

        jLabel11.setText("-");

        jLabel12.setText("-");

        jLabel13.setText("-");

        RezExYear.setEditable(false);
        RezExYear.setText("2019");

        jTextField2.setEditable(false);
        jTextField2.setText("2019");

        RezDoneButton.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        RezDoneButton.setText("Rezervasyonu Tamamla");
        RezDoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RezDoneButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(EkoRadio)
                                .addGap(18, 18, 18)
                                .addComponent(StanRadio)
                                .addGap(18, 18, 18)
                                .addComponent(BSRadio)
                                .addGap(18, 18, 18)
                                .addComponent(KralRadio))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(RezName)
                                    .addComponent(RezSurname)
                                    .addComponent(RezAge)
                                    .addComponent(RezId)
                                    .addComponent(RezPhone)
                                    .addComponent(RezMemnumber, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(RezEnDay, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                    .addComponent(RezExDay))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RezEnMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(RezExMonth)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(RezExYear, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                    .addComponent(jTextField2)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(710, 710, 710)
                        .addComponent(RezDoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(1152, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(RezName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(RezSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(RezAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(RezId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(RezPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(RezMemnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EkoRadio)
                    .addComponent(StanRadio)
                    .addComponent(BSRadio)
                    .addComponent(KralRadio))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(RezEnDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(RezEnMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(RezExDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(RezExMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(RezExYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 378, Short.MAX_VALUE)
                .addComponent(RezDoneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RezDoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RezDoneButtonActionPerformed
        String name=RezName.getText();
        String surname=RezSurname.getText();
        int age=new Integer(RezAge.getText());
        String id=RezId.getText();
        String phone=RezPhone.getText();
        int memnumber=new Integer(RezMemnumber.getText());
        String roomnumber="0";
        String entrydate=RezEnDay.getText()+"-"+RezEnMonth.getText()+"-2019";
        String exitdate=RezExDay.getText()+"-"+RezExMonth.getText()+"-2019";
        int price;
        int day;
        int eko=1,stan=1,bs=1,kral=1;
        boolean ro=false;
        int enMonth=new Integer(RezEnMonth.getText());
        int exMonth=new Integer(RezExMonth.getText());
        int enDay=new Integer(RezEnDay.getText());
        int exDay=new Integer(RezExDay.getText());
        if(enMonth==exMonth){
            day=exDay-enDay+1;
            System.out.println(day);
        }
        else{
            if(exMonth==8){
               day=exDay-enDay+32; 
               System.out.println(day);
            }
            else{
                day=exDay-enDay+31;
                System.out.println(day);
            }
        }
        if(EkoRadio.isSelected()){
            price = 80*day;
            if(eko<=5){
             roomnumber=10+eko+"";
            eko++;   
            }
            else{
                //JOptionPane.showMessageDialog(this, "Seçtiğiniz tarihlerde boş ekonomik odamız bulunmamaktadır...");
                ro=true;
            }
            
          /*  if(ops.emptyRoom("Ekonomik Oda", RezEnDay.getText(), RezEnMonth.getText(), RezExDay.getText(), RezExMonth.getText())>0){
                roomnumber=""+ops.emptyRoom("Ekonomik Oda", RezEnDay.getText(), RezEnMonth.getText(), RezExDay.getText(), RezExMonth.getText());
            }
            else{
                JOptionPane.showMessageDialog(this, "Seçtiğiniz tarihlerde boş ekonomik odamız bulunmamaktadır...");
            }*/
            
        }
        else if(StanRadio.isSelected()){
            price=150*day;
            if(stan<=10){
             roomnumber=20+stan+"";
             stan++;
            }
            else{
                ro=true;
            }
            
          /*  if(ops.emptyRoom("Standart Oda", RezEnDay.getText(), RezEnMonth.getText(), RezExDay.getText(), RezExMonth.getText())>0){
                roomnumber=""+ops.emptyRoom("Standart Oda", RezEnDay.getText(), RezEnMonth.getText(), RezExDay.getText(), RezExMonth.getText());
            }
            else{
                JOptionPane.showMessageDialog(this, "Seçtiğiniz tarihlerde boş standart odamız bulunmamaktadır...");
            }*/
            
        }
        else if(BSRadio.isSelected()){
            price = 250*day;
            if(bs<=10){
             roomnumber=30+bs+"";
             bs++;
            }
            else{
                ro=true;
            }
         /*   if(ops.emptyRoom("Balayı Suiti", RezEnDay.getText(), RezEnMonth.getText(), RezExDay.getText(), RezExMonth.getText())>0){
                roomnumber=""+ops.emptyRoom("Balayı Suiti", RezEnDay.getText(), RezEnMonth.getText(), RezExDay.getText(), RezExMonth.getText());
            }
            else{
                JOptionPane.showMessageDialog(this, "Seçtiğiniz tarihlerde boş balayı suitimiz bulunmamaktadır...");
            }*/
            
        }
        else{
            price = 1200*day;
            if(kral<=1){
             roomnumber="RubyKing";
             kral++;
            }
            else{
                ro=true;
            }
         /*   if(ops.emptyRoom("Kral Dairesi", RezEnDay.getText(), RezEnMonth.getText(), RezExDay.getText(), RezExMonth.getText())>0){
                roomnumber=""+ops.emptyRoom("Kral Dairesi", RezEnDay.getText(), RezEnMonth.getText(), RezExDay.getText(), RezExMonth.getText());
            }
            else{
                JOptionPane.showMessageDialog(this, "Seçtiğiniz tarihlerde boş kral dairemiz bulunmamaktadır...");
            }*/
            
        }
        
        
        
        if((new Integer(RezEnMonth.getText()))>(new Integer(RezExMonth.getText()))){
            JOptionPane.showMessageDialog(this, "Tarihleri Kontrol Ediniz...");
        }
        else if(((new Integer(RezEnMonth.getText()))==(new Integer(RezExMonth.getText())))&&((new Integer(RezEnDay.getText()))>(new Integer(RezExDay.getText())))){
            JOptionPane.showMessageDialog(this, "Tarihleri Kontrol Ediniz...");
        }
        else if(((new Integer(RezEnMonth.getText()))<6)||((new Integer(RezEnMonth.getText()))>8)||((new Integer(RezExMonth.getText()))<6)||((new Integer(RezExMonth.getText()))>8)){
            JOptionPane.showMessageDialog(this, "Otelimiz 1 Haziran - 31 Ağustos arası hizmetinizdedir...");
        }
        else if(age<18){
            JOptionPane.showMessageDialog(this, "18 yaşından küçükler tek başına rezervasyon yapamaz...");
            
        }
        else if((EkoRadio.isSelected()&&memnumber>2)||(StanRadio.isSelected()&&memnumber>4)||(BSRadio.isSelected()&&memnumber>2)||(KralRadio.isSelected()&&memnumber>10)){
            JOptionPane.showMessageDialog(this, "Ekonomik Oda:2\nStandart Oda:4\nBalayı Suiti:2\nKral Dairesi:10\n"
                    + "Kişiliktir bu sayılara göre kişi sayısı giriniz");
        }
        else if(ro){
            JOptionPane.showMessageDialog(this, "Seçtiğiniz tipte boş odamız bulunmamaktadır...");
        }
        else{
            if(age>=60){
            price=(price/100)*80;
            JOptionPane.showMessageDialog(this, "60 yaşüstü kampanyamızdan dolayı %20 indirim kazandınız...");
        }
            ops.addCustomer(name, surname, age, id, phone, memnumber, roomnumber, entrydate, exitdate, price);
          //  ops.roomDate(roomnumber, RezEnDay.getText(), RezEnMonth.getText(), RezExDay.getText(), RezExMonth.getText());
            JOptionPane.showMessageDialog(this, "Rezervasyonunuz Tamamlanmıştır...Oda numaranız "+roomnumber+". Ücretiniz "+price+"TL'dir");
            setVisible(false);
        }
        
    }//GEN-LAST:event_RezDoneButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RezPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RezPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RezPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RezPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RezPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BSRadio;
    private javax.swing.JRadioButton EkoRadio;
    private javax.swing.JRadioButton KralRadio;
    private javax.swing.JTextField RezAge;
    private javax.swing.JButton RezDoneButton;
    private javax.swing.JTextField RezEnDay;
    private javax.swing.JTextField RezEnMonth;
    private javax.swing.JTextField RezExDay;
    private javax.swing.JTextField RezExMonth;
    private javax.swing.JTextField RezExYear;
    private javax.swing.JTextField RezId;
    private javax.swing.JTextField RezMemnumber;
    private javax.swing.JTextField RezName;
    private javax.swing.JTextField RezPhone;
    private javax.swing.JTextField RezSurname;
    private javax.swing.JRadioButton StanRadio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
